### ISSUE TITLE
无法进行正版认证

### ISSUE THREAD

**Issue by MoeShimaKaze** [DoomsdaySociety/DoomsdayVerify#1]
错误日志如下
`[Craft Scheduler Thread - 3891/WARN]: java.io.IOException: Server returned HTTP response code: 403 for URL: https://verify.doomteam.fun/CLIENT_SECRET
[11:39:35] [Craft Scheduler Thread - 3891/WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[11:39:35] [Craft Scheduler Thread - 3891/WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[11:39:35] [Craft Scheduler Thread - 3891/WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[11:39:35] [Craft Scheduler Thread - 3891/WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[11:39:35] [Craft Scheduler Thread - 3891/WARN]:        at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1947)
[11:39:35] [Craft Scheduler Thread - 3891/WARN]:        at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1942)
[11:39:35] [Craft Scheduler Thread - 3891/WARN]:        at java.security.AccessController.doPrivileged(Native Method)
[11:39:35] [Craft Scheduler Thread - 3891/WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1941)
[11:39:35] [Craft Scheduler Thread - 3891/WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1511)
[11:39:35] [Craft Scheduler Thread - 3891/WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1495)
[11:39:35] [Craft Scheduler Thread - 3891/WARN]:        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
[11:39:35] [Craft Scheduler Thread - 3891/WARN]:        at org.jackhuang.hmcl.util.io.HttpRequest$HttpGetRequest.getString(HttpRequest.java:134)
[11:39:35] [Craft Scheduler Thread - 3891/WARN]:        at fun.doomteam.verify.AuthUtil.microsoft(AuthUtil.java:139)
[11:39:35] [Craft Scheduler Thread - 3891/WARN]:        at fun.doomteam.verify.VerifyManager$MicrosoftLoginTask.run(VerifyManager.java:35)
[11:39:35] [Craft Scheduler Thread - 3891/WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
[11:39:35] [Craft Scheduler Thread - 3891/WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[11:39:35] [Craft Scheduler Thread - 3891/WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[11:39:35] [Craft Scheduler Thread - 3891/WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[11:39:35] [Craft Scheduler Thread - 3891/WARN]:        at java.lang.Thread.run(Thread.java:748)
[11:39:35] [Craft Scheduler Thread - 3891/WARN]: Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://verify.doomteam.fun/CLIENT_SECRET
[11:39:35] [Craft Scheduler Thread - 3891/WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1897)
[11:39:35] [Craft Scheduler Thread - 3891/WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1495)
[11:39:35] [Craft Scheduler Thread - 3891/WARN]:        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
[11:39:35] [Craft Scheduler Thread - 3891/WARN]:        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:352)
[11:39:35] [Craft Scheduler Thread - 3891/WARN]:        at org.jackhuang.hmcl.util.io.NetworkUtils.resolveConnection(NetworkUtils.java:117)
[11:39:35] [Craft Scheduler Thread - 3891/WARN]:        at org.jackhuang.hmcl.util.io.HttpRequest$HttpGetRequest.getString(HttpRequest.java:133)
[11:39:35] [Craft Scheduler Thread - 3891/WARN]:        ... 7 more`
使用的账号是从Mojang迁移到微软的正版账户，启动器里设置的是正版登陆
服务端版本为1.12.2 CatServer

**Comment by MoeShimaKaze** [comment]
测试了不同系统环境下的情况，均为一样的错误，Linux和Windows都试过了

**Comment by MrXiaoM** [comment]
无法获取到 CLIENT_SECRET，这是我的问题，在二月的时候我换用了 Gitee 储存 CLIENT_SECRET。但这种方法实在太蠢了，稍后如果我有空研究将可能会采用 hmcl 那种填码到网页登录的方式
